language: generic
os: osx
osx_image: xcode7.3
sudo: false
env:
    matrix:
        - CONDA_PY=27

install:
    - MINICONDA_URL="https://repo.continuum.io/miniconda"
    - MINICONDA_FILE="Miniconda-latest-MacOSX-x86_64.sh"
    - curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
    - bash ${MINICONDA_FILE} -b -p $HOME/miniconda2
    - export PATH="$HOME/miniconda2/bin:$PATH"
    - conda config --set always_yes yes
    - conda config --add channels conda-forge
    - conda config --add channels mikaem/label/OSX-10.11-clang
    - conda update -q conda
    - conda install --yes fenics=2017.1.dev
    - python setup.py install

after_failure:
    - cd $HOME/.instant/error
    - bash /home/travis/build/blechta/fenapack/test/print_compilelog.sh

script:
    - cd $PWD/test/regression
    - python test.py || (cat demo.log; exit 1)
