version: 2
jobs:
  build:
    working_directory: /tmp
    docker:
      - image: quay.io/fenicsproject/dev
      - command: /bin/echo "Force CircleCI to use the image entry point"
    steps:
      - checkout:
          path: ~/fenapack

      - run:
          name: FEniCS version info
          command: python -c'import ffc, dolfin; print(ffc.git_commit_hash(), ffc.ufc_signature(), dolfin.git_commit_hash())'

      - run:
          name: Install FENaPack
          working_directory: ~/fenapack/
          command: pip install -v .

      - run:
          name: Unit tests
          working_directory: ~/fenapack/test/unit
          command: py.test -svl --junitxml /tmp/test-results/report.xml

      - run:
          name: Unit tests MPI
          working_directory: ~/fenapack/test/unit
          command: mpirun -n 2 py.test -svl

      - run:
          name: Bench
          working_directory: ~/fenapack/test/bench
          command: py.test -svl

      - run:
          name: Regression tests
          working_directory: ~/fenapack/test/regression
          command: NP=2 python -u test.py

      - store_artifacts:
          path: /tmp/artifacts
          prefix: build

      - store_test_results:
          path: /tmp/test-results
