version: 2
jobs:
  build:
    docker:
      - image: quay.io/fenicsproject/dev
        user: fenics
        environment:
          LD_LIBRARY_PATH: /home/fenics/local/lib
          CMAKE_PREFIX_PATH: /home/fenics/local
    working_directory: /home/fenics/fenapack
    steps:
      - checkout

      - run:
          name: Environment and FEniCS version info
          command: |
              echo $USER $HOME $PWD $PATH $LD_LIBRARY_PATH $CMAKE_PREFIX_PATH
              python -c'import ffc; print(ffc.git_commit_hash(), ffc.ufc_signature())'
              python -c'import dolfin; print(dolfin.git_commit_hash())'

      - run:
          name: Install FENaPack
          command: |
              ./download-meshes
              pip2 install -v --user .

      - run:
          name: Import FENaPack first time (JIT)
          command: python -c"import fenapack"

      - run:
          name: Unit tests
          command: py.test test/unit -svl --junitxml /tmp/test-results/report.xml

      - run:
          name: Unit tests MPI
          command: mpirun -n 2 py.test test/unit -svl

      - run:
          name: Bench
          command: py.test test/bench -svl

      - run:
          name: Regression tests
          command: |
              cd test/regression
              NP=2 python -u test.py

      - store_artifacts:
          path: /tmp/artifacts
          prefix: build

      - store_test_results:
          path: /tmp/test-results
